// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vscode from "vscode";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as $$Node from "vscode-languageclient/node";

var client = {
  contents: undefined
};

function startLanguageClient(context) {
  var config = Vscode.workspace.getConfiguration("anvomidav");
  var path = config.get("lsp.path");
  var serverPath = path !== undefined ? path : "anv-lsp";
  var serverOptions_run = {
    command: serverPath,
    transport: 0
  };
  var serverOptions_debug = {
    command: serverPath,
    transport: 0
  };
  var serverOptions = {
    run: serverOptions_run,
    debug: serverOptions_debug
  };
  var clientOptions_documentSelector = [{
      scheme: "file",
      language: "anvomidav"
    }];
  var clientOptions_synchronize = {
    fileEvents: Vscode.workspace.createFileSystemWatcher("**/*.anv")
  };
  var clientOptions = {
    documentSelector: clientOptions_documentSelector,
    synchronize: clientOptions_synchronize
  };
  var languageClient = new $$Node.LanguageClient("anvomidav", "Anvomidav Language Server", serverOptions, clientOptions);
  client.contents = Caml_option.some(languageClient);
  languageClient.start();
}

function restartServer(context) {
  var c = client.contents;
  if (c !== undefined) {
    Caml_option.valFromOption(c).stop();
    return startLanguageClient(context);
  } else {
    return startLanguageClient(context);
  }
}

function showInfo() {
  Vscode.window.showInformationMessage("Anvomidav LSP extension");
}

function activate(context) {
  startLanguageClient(context);
  var restartCmd = Vscode.commands.registerCommand("anvomidav.restart", (function () {
          return new Promise((function (resolve, param) {
                        restartServer(context);
                        resolve();
                      }));
        }));
  var infoCmd = Vscode.commands.registerCommand("anvomidav.showInfo", (function () {
          return new Promise((function (resolve, param) {
                        Vscode.window.showInformationMessage("Anvomidav LSP extension");
                        resolve();
                      }));
        }));
  context.subscriptions.push(restartCmd);
  context.subscriptions.push(infoCmd);
}

function deactivate() {
  var c = client.contents;
  if (c !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(c).stop());
  }
  
}

export {
  client ,
  startLanguageClient ,
  restartServer ,
  showInfo ,
  activate ,
  deactivate ,
}
/* vscode Not a pure module */
