// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vscode from "vscode";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Node from "vscode-languageclient/node";

let Window = {};

let Commands = {};

let Workspace = {};

let VsCode = {
  Window: Window,
  Commands: Commands,
  Workspace: Workspace
};

let Lsp = {};

let client = {
  contents: undefined
};

function getServerPath() {
  let config = Vscode.workspace.getConfiguration("anvomidav");
  return config.get("lspPath", "anv-lsp");
}

function getDebuggerPath() {
  let config = Vscode.workspace.getConfiguration("anvomidav");
  return config.get("debuggerPath", "anv-debug");
}

async function runProgram() {
  let editor = Vscode.window.activeTextEditor;
  if (editor === undefined) {
    return await Vscode.window.showErrorMessage("No active editor");
  }
  let doc = editor.document;
  if (doc.languageId !== "anvomidav") {
    return await Vscode.window.showErrorMessage("Not an Anvomidav file");
  }
  await doc.save();
  let terminal = Vscode.window.createTerminal("Anvomidav");
  terminal.show();
  return terminal.sendText(`anv run "` + doc.fileName + `"`);
}

async function visualizeChoreography() {
  let editor = Vscode.window.activeTextEditor;
  if (editor === undefined) {
    return await Vscode.window.showErrorMessage("No active editor");
  }
  let doc = editor.document;
  if (doc.languageId !== "anvomidav") {
    return await Vscode.window.showErrorMessage("Not an Anvomidav file");
  }
  await doc.save();
  let outputPath = doc.fileName.replace(/\.anv$/, ".svg");
  let terminal = Vscode.window.createTerminal("Anvomidav Visualize");
  terminal.show();
  terminal.sendText(`anv visualize "` + doc.fileName + `" -o "` + outputPath + `"`);
  return await Vscode.window.showInformationMessage(`Visualization saved to ` + outputPath);
}

async function validateISU() {
  let editor = Vscode.window.activeTextEditor;
  if (editor === undefined) {
    return await Vscode.window.showErrorMessage("No active editor");
  }
  let doc = editor.document;
  if (doc.languageId !== "anvomidav") {
    return await Vscode.window.showErrorMessage("Not an Anvomidav file");
  }
  await doc.save();
  let terminal = Vscode.window.createTerminal("Anvomidav Validate");
  terminal.show();
  return terminal.sendText(`anv validate "` + doc.fileName + `"`);
}

async function debugProgram() {
  let editor = Vscode.window.activeTextEditor;
  if (editor === undefined) {
    return await Vscode.window.showErrorMessage("No active editor");
  }
  let doc = editor.document;
  if (doc.languageId !== "anvomidav") {
    return await Vscode.window.showErrorMessage("Not an Anvomidav file");
  }
  await doc.save();
  let debuggerPath = getDebuggerPath();
  let terminal = Vscode.window.createTerminal("Anvomidav Debug");
  terminal.show();
  terminal.sendText(debuggerPath);
  return terminal.sendText(`load "` + doc.fileName + `"`);
}

function activate(context) {
  console.log("Anvomidav extension activated");
  let serverOptions_command = getServerPath();
  let serverOptions_args = [];
  let serverOptions = {
    command: serverOptions_command,
    args: serverOptions_args,
    transport: 1
  };
  let clientOptions_documentSelector = [{
      scheme: "file",
      language: "anvomidav"
    }];
  let clientOptions_synchronize = {
    fileEvents: Vscode.workspace.createFileSystemWatcher("**/*.anv")
  };
  let clientOptions = {
    documentSelector: clientOptions_documentSelector,
    synchronize: clientOptions_synchronize
  };
  let c = new Node.LanguageClient("anvomidavLanguageServer", "Anvomidav Language Server", serverOptions, clientOptions);
  client.contents = Primitive_option.some(c);
  c.start();
  context.subscriptions.push(Vscode.commands.registerCommand("anvomidav.run", runProgram));
  context.subscriptions.push(Vscode.commands.registerCommand("anvomidav.visualize", visualizeChoreography));
  context.subscriptions.push(Vscode.commands.registerCommand("anvomidav.validate", validateISU));
  context.subscriptions.push(Vscode.commands.registerCommand("anvomidav.debug", debugProgram));
}

function deactivate() {
  let c = client.contents;
  if (c !== undefined) {
    return Primitive_option.valFromOption(c).stop();
  } else {
    return Promise.resolve();
  }
}

export {
  VsCode,
  Lsp,
  client,
  getServerPath,
  getDebuggerPath,
  runProgram,
  visualizeChoreography,
  validateISU,
  debugProgram,
  activate,
  deactivate,
}
/* vscode Not a pure module */
