// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vscode from "vscode";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Node from "vscode-languageclient/node";

let client = {
  contents: undefined
};

function startLanguageClient(context) {
  let config = Vscode.workspace.getConfiguration("anvomidav");
  let path = config.get("lsp.path");
  let serverPath = path !== undefined ? path : "anv-lsp";
  let serverOptions_run = {
    command: serverPath,
    transport: 0
  };
  let serverOptions_debug = {
    command: serverPath,
    transport: 0
  };
  let serverOptions = {
    run: serverOptions_run,
    debug: serverOptions_debug
  };
  let clientOptions_documentSelector = [{
      scheme: "file",
      language: "anvomidav"
    }];
  let clientOptions_synchronize = {
    fileEvents: Vscode.workspace.createFileSystemWatcher("**/*.anv")
  };
  let clientOptions = {
    documentSelector: clientOptions_documentSelector,
    synchronize: clientOptions_synchronize
  };
  let languageClient = new Node.LanguageClient("anvomidav", "Anvomidav Language Server", serverOptions, clientOptions);
  client.contents = Primitive_option.some(languageClient);
  languageClient.start();
}

function restartServer(context) {
  let c = client.contents;
  if (c !== undefined) {
    Primitive_option.valFromOption(c).stop();
    return startLanguageClient(context);
  } else {
    return startLanguageClient(context);
  }
}

function showInfo() {
  Vscode.window.showInformationMessage("Anvomidav LSP extension v0.1.0");
}

function validateProgram() {
  Vscode.window.showInformationMessage("Program validation triggered");
}

function formatDocument() {
  Vscode.window.showInformationMessage("Document formatting not yet fully implemented");
}

function activate(context) {
  startLanguageClient(context);
  let restartCmd = Vscode.commands.registerCommand("anvomidav.restart", () => new Promise((resolve, param) => {
    restartServer(context);
    resolve();
  }));
  let infoCmd = Vscode.commands.registerCommand("anvomidav.showInfo", () => new Promise((resolve, param) => {
    Vscode.window.showInformationMessage("Anvomidav LSP extension v0.1.0");
    resolve();
  }));
  let validateCmd = Vscode.commands.registerCommand("anvomidav.validateProgram", () => new Promise((resolve, param) => {
    Vscode.window.showInformationMessage("Program validation triggered");
    resolve();
  }));
  let formatCmd = Vscode.commands.registerCommand("anvomidav.formatDocument", () => new Promise((resolve, param) => {
    Vscode.window.showInformationMessage("Document formatting not yet fully implemented");
    resolve();
  }));
  context.subscriptions.push(restartCmd);
  context.subscriptions.push(infoCmd);
  context.subscriptions.push(validateCmd);
  context.subscriptions.push(formatCmd);
}

function deactivate() {
  let c = client.contents;
  if (c !== undefined) {
    return Primitive_option.valFromOption(c).stop();
  }
}

export {
  client,
  startLanguageClient,
  restartServer,
  showInfo,
  validateProgram,
  formatDocument,
  activate,
  deactivate,
}
/* vscode Not a pure module */
